name: Build nginx
on:
  push:
    branches: [ master ]
    paths:
      - 'nginx/**'
      - '.github/workflows/nginx.yml'
jobs:
  build:
    name: Build container
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: manual_kaniko_build
        run: >
          docker run
          -v ~/.docker:/kaniko/.docker
          -v $(pwd)/php:/context
          gcr.io/kaniko-project/executor
          --context dir:///context/
          --destination ghcr.io/herams-who/docker/nginx:${{ github.sha }}
          --destination ghcr.io/herams-who/docker/nginx:latest
          --build-arg COMMIT_SHA=${{ github.sha }}
          --use-new-run
      - id: kaniko_build
        name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          password: ${{ secrets.GHCR_TOKEN }}
          tag: ${{ github.sha }}
          tag_with_latest: true
          extra_args: "--build-arg COMMIT_SHA=${{ github.sha }} --use-new-run"
          image: herams-who/docker/nginx
          build_file: nginx/Dockerfile
