name: Build nginx v2
on:
  push:
    branches: [ master ]
    paths:
      - 'nginx-v2/**'
      - '.github/workflows/nginx-v2.yml'
permissions:
  packages: write
jobs:
  build:
    name: Build container v2
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images v2
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          context: nginx-v2/
          tags: |
            ghcr.io/herams-who/docker/nginx-v2:${{ github.sha }}
            ghcr.io/herams-who/docker/nginx-v2:latest
