name: Build php
on:
  push:
    branches: [ master ]
    paths:
      - 'php/**'
      - '.github/workflows/php.yml'
jobs:
  build:
    name: Build container
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.9.0
        with:
          push: true
          context: php
          build-args: |
            COMMIT_SHA=${{ github.sha }}
          tags: |
            ghcr.io/herams-who/docker/php:${{ github.sha }}
            ghcr.io/herams-who/docker/php:latest