name: Build php
on:
  push:
    branches: [ master ]
    paths:
      - 'php/**'
      - '.github/workflows/php.yml'
jobs:
  build:
    name: Build container
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          push: true
          context: php
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            COMMIT_SHA=${{ github.sha }}
          tags: |
            ghcr.io/herams-who/docker/php:${{ github.sha }}
            ghcr.io/herams-who/docker/php:latest
