name: Build php
on:
  push:
    branches: [ master ]
    paths:
      - 'php/**'
      - '.github/workflows/php.yml'
jobs:
  build:
    name: Build container
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: docker_build
        env:
          DOCKER_BUILDKIT: "1"
        working-directory: php
        run: >
          docker build .
          --pull
          -t ghcr.io/herams-who/docker/php:${{ github.sha }}
          -t ghcr.io/herams-who/docker/php:latest
          --build-arg COMMIT_SHA=${{ github.sha }}