name: Build php
on:
  push:
    branches: [ master ]
    paths:
      - 'php/**'
      - '.github/workflows/php.yml'
jobs:
  build:
    name: Build container
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: test_empty_push
        run: docker pull alpine && docker tag alpine ghcr.io/herams-who/docker/php:${{ github.sha }} && docker push ghcr.io/herams-who/docker/php:${{ github.sha }}
      - id: manual_kaniko_build
        run: >
          docker run
          -v ~/.docker:/kaniko/.docker
          -v $(pwd)/php:/context
          gcr.io/kaniko-project/executor
          --context dir:///context/
          --destination ghcr.io/herams-who/docker/php:${{ github.sha }}
          --destination ghcr.io/herams-who/docker/php:latest
          --build-arg COMMIT_SHA=${{ github.sha }}
          --use-new-run
