name: Build php v2
on:
  push:
    branches: [ master ]
    paths:
      - 'v2/php/**'
      - '.github/workflows/php_v2.yml'
jobs:
  build:
    name: Build container v2
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images v2
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          context: v2/php
          build-args: |
            COMMIT_SHA=${{ github.sha }}
          tags: |
            ghcr.io/herams-who/docker/php_v2:${{ github.sha }}
            ghcr.io/herams-who/docker/php_v2:latest
