name: Build phpfpm
on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/phpfpm.yml'
      - 'phpfpm/**'
jobs:
  build:
    name: Build container
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          push: true
          context: .
          file: phpfpm/Dockerfile
          tags: |
            ghcr.io/herams-who/docker/phpfpm:${{ github.sha }}
            ghcr.io/herams-who/docker/phpfpm:latest
