name: Build phpfpm
on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/phpfpm.yml'
      - 'phpfpm/**'
permissions:
  packages: write
jobs:
  build:
    name: Build container
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          push: true
          context: .
          file: phpfpm/Dockerfile
          tags: |
            ghcr.io/herams-who/docker/phpfpm:${{ github.sha }}
            ghcr.io/herams-who/docker/phpfpm:latest
