name: Build phpfpm v2
on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/phpfpm-v2.yml'
      - 'phpfpm-v2/**'
permissions:
  packages: write
jobs:
  build:
    name: Build container v2
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Build and push Docker images v2
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          context: .
          file: phpfpm-v2/Dockerfile
          tags: |
            ghcr.io/herams-who/docker/phpfpm-v2:${{ github.sha }}
            ghcr.io/herams-who/docker/phpfpm-v2:latest
